Fix type of base parameter in the makeCollapsedIndex function
This fixes the following error when something else than `int` is used
for `IndexType` in `Grid`:

```
error: no matching function for call to ‘makeCollapsedIndex(const int&, const TNL::Meshes::Grid<1, double, TNL::Devices::Host, long int>::CoordinatesType&)’
...
note:   deduced conflicting types for parameter ‘Index’ (‘int’ and ‘long int’)
```